#!/bin/bash

fileQuestions="/quiz/questions"
varOddEven=1

echo "var questions = ["

while read -r line; do
	if (( varOddEven % 2 != 0 )); then
		echo "	{"
		echo "		question: $line,"
		(( varOddEven++ ))
	else
		echo "		answer: $line,"
		echo "	},"
		(( varOddEven++ ))
	fi
done

echo "];"
